"""empty message

Revision ID: 5fffee9ee53a
Revises: a9badb0424b5
Create Date: 2021-05-23 22:05:07.676529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fffee9ee53a'
down_revision = 'a9badb0424b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dostepnosc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=100), nullable=True),
    sa.Column('date_borrow', sa.Date(), nullable=True),
    sa.Column('date_return', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['ksiazka.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dostepnosc')
    # ### end Alembic commands ###
