"""empty message

Revision ID: 674f51306ca8
Revises: 5e437469d948
Create Date: 2021-05-23 19:22:53.966793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674f51306ca8'
down_revision = '5e437469d948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ksiazka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ksiazka_title'), 'ksiazka', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ksiazka_title'), table_name='ksiazka')
    op.drop_table('ksiazka')
    op.drop_table('autor')
    # ### end Alembic commands ###
