"""empty message

Revision ID: a9badb0424b5
Revises: 674f51306ca8
Create Date: 2021-05-23 19:51:17.538232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9badb0424b5'
down_revision = '674f51306ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_author',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['ksiazka.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_author')
    # ### end Alembic commands ###
